zmodload zsh/zprof
# run the below command to profile the zsh startup time and see where the time is being spent
# zprof

# ---------------------------------------------------------------------------
# OH MY ZSH CONFIGURATION START
# ---------------------------------------------------------------------------

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"

# im using starship so this will be empty
ZSH_THEME=""

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
# for custom plugins: https://github.com/zsh-users

# here's how i installed custom plugins:
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# git clone https://github.com/zsh-users/zsh-completions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-completions
# git clone https://github.com/zsh-users/zsh-history-substring-search.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

plugins=(
    autopep8
    colored-man-pages
    colorize
    command-not-found
    docker
    docker-compose
    emoji
    fzf
    gh
    git
    git-commit
    sudo
    zsh-autosuggestions
    zsh-completions
    zsh-history-substring-search
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# ---------------------------------------------------------------------------
# OH MY ZSH CONFIGURATION END
# ---------------------------------------------------------------------------

# i think i dont need this since i have the array above of plugins. i clonded the plugins from their repos
# https://github.com/zsh-users
# source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# source <(fzf --zsh)
# source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh
# source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ---------------------------------------------------------------------------
# NVM (NODE VERSION MANAGER)
# ---------------------------------------------------------------------------
# >>> nvm initialize >>>
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# <<< end nvm initialize <<<


# ---------------------------------------------------------------------------
# PROMPT - CUSTOM
# ---------------------------------------------------------------------------

# Git branch in prompt.
# function parse_git_branch() {
#     git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/[\1]/p'
# }

# COLOR_DEF=$'\e[0m'
# COLOR_USR=$'\e[38;5;243m'
# COLOR_DIR=$'\e[38;5;197m'
# COLOR_GIT=$'\e[38;5;39m'
# setopt PROMPT_SUBST

# #option4b
# export PROMPT='%F{green}%n %F{blue}%. %F{magenta}$(parse_git_branch) %F{grey}%% '

# autoload -U colors && colors
# # enable color support of ls and also add handy aliases
#   if [ -x /usr/bin/dircolors ]; then
#       test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#       alias ls='ls --color=auto'
#       alias dir='dir --color=auto'
#       alias vdir='vdir --color=auto'
#       alias grep='grep --color=auto'
#       alias fgrep='fgrep --color=auto'
#       alias egrep='egrep --color=auto'
#   fi



# ---------------------------------------------------------------------------
# PROMPT - STARSHIP
# ---------------------------------------------------------------------------
export STARSHIP_CONFIG=~/.config/starship.toml
# prompt theme: https://github.com/starship/starship
eval "$(starship init zsh)"


uuid() {
  # Generate the UUID and store it in a variable
  local id
  id=$(python -c "import uuid; print(uuid.uuid4(), end='')")

  # Print the clean UUID to the clipboard without a newline
  printf "%s" "$id" | pbcopy

  # Print the UUID to the terminal with a newline for a clean display
  echo "$id"
}


alias gst='git status'

# git stash --include-untracked
alias gsu='git stash -u'

alias gdf='git diff --staged'

alias up='cd ..'

# Source local/machine-specific config (not in dotfiles repo)
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Added by arine-server/bin/setup
eval "$(direnv hook zsh)"
